### ISSUE TITLE
new release is long overdue

### ISSUE THREAD

**Issue by msimerson** [schamane/node-syslog#37]
Is there anything I can do to nudge that along?

**Comment by lbeschastny** [comment]
I think, you should release it under some short unique memorable name, something like `stronglog`.

It'll be a good idea to rename github repo, too. In this case all links from deprecated `npm` packages will lead ti the new repo with new name.

**Comment by sam-github** [comment]
https://github.com/sam-github/modern-syslog/pull/1

**Comment by lbeschastny** [comment]
@sam-github I was talking about renaming existing repo, not creating a new one. The main reason to rename current repo is because GitHub will add automatic redirects for all old links with the old repo name to the new one. It'll also keep the history of all previous commits, which could be useful.

Though, if you're going to re-implement `node-syslog` from the scratch, then you won't need commits history. And since you have access to this repo, you could always place a big deprecation warning with the link to the new one.

**Comment by gabrielschulhof** [comment]
@schamane if you're still around, is there any chance you could publish a new version on npm? This is a really useful package, but it currently fails to build beyond node-v0.10.

**Comment by schamane** [comment]
Hi, i will try to find some solution to this. Sorry...

**Comment by gabrielschulhof** [comment]
@schamane Awesome! Thanks so much!

**Comment by schamane** [comment]
I just published updated package version to npm. Can someone test if it work and give me feedback here?
Thanks.

**Comment by gabrielschulhof** [comment]
Works with node v0.10 and v0.12, AFAICT.

**Comment by gabrielschulhof** [comment]
@schamane I suppose you can close this issue :)
